"""Regression tests for reference resolution.

Both cases here were found by running the extractor against the real Sales &
Returns model rather than by reasoning about the DAX spec, which is why they are
pinned: the first was a genuine bug, the second is a limit of what a .pbix
exposes and must stay visible instead of being silently dropped.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from concordance.adapters.pbix import PbixAdapter
from concordance.graph.csg import SemanticGraph, measure_id

MODEL = Path("data/models/Sales_Returns_Sample.pbix")


@pytest.fixture(scope="module")
def graph() -> SemanticGraph:
    if not MODEL.exists():
        pytest.skip(f"sample model not present: {MODEL}")
    return SemanticGraph(PbixAdapter().extract(str(MODEL)))


def test_qualified_measure_reference_resolves_as_a_measure(graph: SemanticGraph) -> None:
    """'% Return Rate'[% Return Rate Value] is a measure, despite the qualifier.

    DAX discourages qualifying measure references but permits them, and this
    model does it. Treating every Table[Name] as a column silently lost the
    dependency edge and reported a phantom missing column.
    """
    measure = next(
        m for m in graph.model.measures if m.name == "WIF Adjusted Net Sales"
    )
    assert "% Return Rate Value" in measure.depends_on_measures
    assert not any(
        name == "% Return Rate Value" for _, name in measure.depends_on_columns
    )

    edge_targets = graph.dependencies_of(
        measure_id(measure.table, measure.name)
    )
    assert any(t.endswith("[% Return Rate Value]") for t in edge_targets)


def test_what_if_parameter_column_is_reported_with_a_precise_reason(
    graph: SemanticGraph,
) -> None:
    """The parameter table's own column genuinely is not in the stored schema.

    It is generated by GENERATESERIES and never materialises into VertiPaq, so
    the honest outcome is an unresolved reference that says why -- not a
    dropped edge, and not a misleading 'column not found'.
    """
    reasons = {
        u.reason for u in graph.unresolved if "% Return Rate" in u.target
    }
    assert reasons, "expected the what-if parameter reference to remain unresolved"
    assert all("calculated/parameter table" in r for r in reasons), reasons


def test_measure_only_tables_are_registered_as_real_nodes(graph: SemanticGraph) -> None:
    """PBIXRay omits tables that store no data, and they hold most of the measures.

    Without this, the graph grows attribute-less placeholder nodes and every
    measure in 'Analysis DAX' is orphaned from its parent table.
    """
    names = {t.name for t in graph.model.tables}
    assert {"Analysis DAX", "Design DAX", "% Return Rate"} <= names

    measure_only = {t.name for t in graph.model.tables if t.is_measure_only}
    assert {"Analysis DAX", "Design DAX"} <= measure_only
    assert "Sales" not in measure_only

    untyped = [n for n, d in graph.graph.nodes(data=True) if not d.get("kind")]
    assert not untyped, f"placeholder nodes with no attributes: {untyped}"


def test_date_hierarchy_level_is_not_treated_as_a_separate_object(
    graph: SemanticGraph,
) -> None:
    """'Calendar'[Date].[Month] depends on Calendar[Date], not on a [Month] object."""
    measure = next(m for m in graph.model.measures if m.name == "WIF Sales")
    assert ("Calendar", "Date") in measure.depends_on_columns
    assert not any(
        name == "Month" for _, name in measure.depends_on_columns
    ), measure.depends_on_columns
    assert "Month" not in measure.depends_on_measures


def test_hierarchy_level_still_affects_the_fingerprint() -> None:
    """Skipping the level for dependencies must not make .[Month] and .[Year] equal."""
    from concordance.fingerprint import fingerprint_dax

    month = fingerprint_dax("CALCULATE([S], ALL('Calendar'[Date].[Month]))")
    year = fingerprint_dax("CALCULATE([S], ALL('Calendar'[Date].[Year]))")
    assert month != year


def test_unresolved_references_are_few_and_all_explained(graph: SemanticGraph) -> None:
    """A real model should resolve almost everything; anything left needs a reason."""
    valid = {
        "table not in model",
        "calculated/parameter table -- columns not in stored schema",
        "column not found in table",
        "measure not found",
    }
    assert all(u.reason in valid for u in graph.unresolved)
    resolvable = len(graph.model.measures) + len(graph.model.columns)
    assert len(graph.unresolved) < resolvable * 0.05, (
        f"{len(graph.unresolved)} unresolved is too many to be incidental"
    )
